### ISSUE TITLE
AttributeError: object has no attribute '_friendly_name_internal' on all entities during setup

### ISSUE THREAD

**Issue by 308Chaucer** [pyalarmdotcom/alarmdotcom#540]
`<p><strong>Title:</strong> <code>AttributeError: object has no attribute '_friendly_name_internal'</code> on all entities during setup</p>

<h3>Describe the bug</h3>
<p>The integration successfully authenticates and retrieves the device list from Alarm.com, but fails completely during entity creation. None of the entities populate in Home Assistant.</p>
<p>Every device type (<code>AlarmControlPanel</code>, <code>BinarySensor</code>, <code>AttributeBinarySensor</code>, <code>Cover</code>, <code>DebugButton</code>, <code>Climate</code>) throws an <code>AttributeError: object has no attribute '_friendly_name_internal'</code> crash during <code>_async_add_entity</code>[cite: 1].</p>

<h3>Steps to Reproduce</h3>
<ol>
  <li>Install and configure the Alarm.com integration.</li>
  <li>Restart Home Assistant.</li>
  <li>The integration initializes and successfully fetches system data.</li>
  <li>Entity creation fails, throwing <code>AttributeError</code> for every device, resulting in unavailable entities and no data updates.</li>
</ol>

<h3>Expected behavior</h3>
<p>Entities should be created successfully without attribute errors so that state updates can be received and displayed in Home Assistant.</p>

<h3>Relevant log output</h3>
<p>The core error is identical across all domains[cite: 1]. Here is the traceback for the Alarm Control Panel (full log attached):</p>

<pre><code>2026-06-08 13:31:15.689 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarmdotcom.alarm_control_panel
2026-06-08 13:31:15.689 INFO (MainThread) [custom_components.alarmdotcom.base_device] custom_components.alarmdotcom.base_device: Initializing [partition: Panel (106899236-127)].
2026-06-08 13:31:15.703 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error adding entity alarm_control_panel.panel for domain alarm_control_panel with platform alarmdotcom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 716, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1048, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1439, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/alarmdotcom/base_device.py", 

[home-assistant_2026-06-09T00-35-26.250Z.log](https://github.com/user-attachments/files/28730841/home-assistant_2026-06-09T00-35-26.250Z.log)

line 74, in async_added_to_hass
    self._update_device_data()
  File "/config/custom_components/alarmdotcom/base_device.py", line 106, in _update_device_data
    f"Updated {self.device_type_name} {self._friendly_name_internal()} ({self._adc_id}): {self.state}"
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AlarmControlPanel' object has no attribute '_friendly_name_internal'</code></pre>

<h3>Additional Context</h3>
<ul>
  <li><strong>Home Assistant Version:</strong> 2026.6.1[cite: 1]</li>
  <li><strong>Full Log:</strong> See attached <code>home-assistant_2026-06-09T00-35-26.250Z.log</code> file.</li>
  <li>The logs also show a deprecation warning right before the crashes: <code>Detected that custom integration 'alarmdotcom' calls device_registry.async_get_or_create referencing a non existing via_device ('alarmdotcom', None)... This will stop working in Home Assistant 2025.12.0</code>[cite: 1]</li>
</ul>`

**Comment by BonasortCL** [comment]
Confirming the root cause and sharing a fix for anyone hitting this on **Home Assistant 2026.x** 👇

**Root cause:** HA removed the internal `Entity._friendly_name_internal()` method in 2026.2 (core PR #162766). `base_device.py` still calls it in the per-update log line (`_update_device_data`, ~line 106), so `async_added_to_hass` raises `AttributeError` for every entity and nothing loads. A few more 2026.x breakages sit behind it: alarm panel `state`→`alarm_state`, light `COLOR_MODE_*`→`ColorMode`, climate `AUX_HEAT` removal + missing `TURN_ON/OFF`, `OptionsFlow.config_entry` (read-only since 2025.12), config-entry `version` assignment, the `via_device` deprecation, and a shutdown `TypeError`.

**I patched all of them** in a fork and have been running it on HA 2026.6.2 — all entities load and stay available. I also fixed a separate bug in the `pyalarmdotcomajax` library that was tearing down the WebSocket, which restores near-real-time push (events in ~1s instead of waiting for polling).

### If you just want it working now (HACS)

The original and the fork share the same `domain`, so **remove the current Alarm.com from HACS first**, then:

1. HACS → ⋮ → **Custom repositories** → add `https://github.com/Bonasort-HA/alarmdotcom` (category: **Integration**).
2. Download **Alarm.com**, restart Home Assistant.
3. The fork pulls its patched library automatically — nothing else to install. Your existing entities/config are kept (same domain).

### For the maintainers (@uvjustin @elahd)

Thanks for building this 🙏 The fixes are small and self-contained, all MIT like upstream — happy to open PRs if that's useful. Two repos:

- Integration: https://github.com/Bonasort-HA/alarmdotcom
- Library (WebSocket fix): https://github.com/Bonasort-HA/pyalarmdotcomajax

Feel free to cherry-pick anything.

**Comment by 43976989** [comment]
Main thread/issue: https://github.com/pyalarmdotcom/alarmdotcom/issues/509

There's also https://github.com/ibasebcast/ha-alarmdotcom which has a working version

**Comment by ScottieP13** [comment]
I was able to reproduce this on Home Assistant 2026.7.2 with Alarm.com v3.0.15.

In my environment, replacing self._friendly_name_internal() with self.device.name in custom_components/alarmdotcom/base_device.py restored normal operation in my environment after restarting Home Assistant. 

I verified the following after making the change:

Alarm panel updates normally
Door and window sensors update correctly
Schlage lock state updates correctly
Lock/unlock commands work normally
Garage door entities update correctly

I haven't confirmed whether self.device.name is the preferred long-term implementation, but it resolved the issue in my environment and may help narrow down a permanent fix.

If it would be helpful, I'd also be happy to test a proposed fix or submit a pull request once the preferred implementation is confirmed.
